# Generated by Django 5.2.17 on 2026-10-06 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_number', models.PositiveIntegerField()),
                ('interview_type', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('question_time_limit', models.PositiveIntegerField(default=120)),
                ('focus_area', models.CharField(blank=True, max_length=100, null=True)),
                ('target_role', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'interview_number'), name='unique_interview_number_per_user')],
            },
        ),
    ]
