# Generated by Django 5.2.17 on 2026-10-06 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('interviewer', 'Interviewer'), ('user', 'User')], max_length=20)),
                ('content', models.TextField()),
                ('message_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('asked', 'Asked'), ('answered', 'Answered'), ('skipped', 'Skipped')], default='asked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interviews.interview')),
            ],
        ),
    ]
