# Generated by Django 5.2.17 on 2026-10-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='interview',
            name='years_of_experience',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('non_technical', 'Non-Technical'), ('behavioral', 'Behavioral')], max_length=20),
        ),
    ]
