# Generated by Django 5.2.17 on 2026-10-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_remove_interview_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='question_count',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
