# Generated by Django 5.2.17 on 2026-10-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_interview_question_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='question_count',
        ),
    ]
