# Generated by Django 5.2.17 on 2026-10-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_remove_interview_question_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='question_count',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
